#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"

. ${basedir}/package-manager

read -r -p "Do you want to enable the firewall ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    ${package_manager} --noconfirm -S \
        ufw \
        firewalld
    
    sudo systemctl enable --now ufw.service
    sudo ufw enable
fi

echo "Installing default packages"
. ${basedir}/packages-list
${package_manager} --noconfirm -S $packages

read -r -p "Do you want to enable amdgpu hardware audio/video decoding ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    . ${basedir}/amd-va-packages-list
    ${package_manager} --noconfirm -S $amd_va_packages
    echo "Hardware Audio/Video acceleration enabled !"
fi